networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "7001:80"
      - "7443:443"  # HTTPS port mapping
    volumes:
      - ./dockerize_laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dockerize_laravel/nginx/certs:/etc/nginx/certs  # Mount certificates
      - .:/var/www/app:delegated
    depends_on:
      - cinema_scope
    networks:
      - laravel

  cinema_scope:
    build:
      context: .
      dockerfile: dockerize_laravel/php/Dockerfile
    container_name: CinemaScope
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - .:/var/www/app:delegated
    networks:
      - laravel

#  vue:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: vue
#    ports:
#      - '5173:5173'
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    environment:
#      - VITE_API_BASE_URL=https://localhost:7001//api
#      - NODE_ENV=development
#    networks:
#      - laravel

  database:
    image: mysql:latest
    container_name: database
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
volumes:
  dbdata:
    driver: local
